--- #YAML:1.0
name:                Catalyst-Plugin-RequestToken
version:             0.05
abstract:            Module abstract (<= 44 characters) goes here
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Catalyst:                      5.5
    Catalyst::Plugin::Session:     0
    Digest:                        0
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Hideo Kimura (hide@hide-k.net)
